CREATE OR REPLACE FUNCTION CLB239950.F_FILE_DOES_EXIST(LOCATION IN VARCHAR2,FILENAME IN VARCHAR2)
RETURN BOOLEAN AS

V_FILE_HANDLE UTL_FILE.FILE_TYPE;

BEGIN
	 V_FILE_HANDLE := UTL_FILE.FOPEN(LOCATION,FILENAME,'R');
	 RETURN TRUE;
	 UTL_FILE.FCLOSE(V_FILE_HANDLE);

EXCEPTION
		 WHEN OTHERS THEN
		 	  RETURN FALSE;
END F_FILE_DOES_EXIST;
/
