CREATE OR REPLACE FUNCTION CLB239950.F_IS_DATE(
   P_TESTE   IN VARCHAR2,
   P_FORMATO IN VARCHAR2  DEFAULT 'dd/mm/yyyy'
)
RETURN NUMBER
IS
   V_DATA DATE;
BEGIN
   SELECT TO_DATE( P_TESTE, P_FORMATO )
   INTO V_DATA
   FROM DUAL;

   RETURN 1;

EXCEPTION
   WHEN OTHERS THEN
      RETURN 0;
END F_IS_DATE;
/
