CREATE OR REPLACE
FUNCTION         PRESTACOES
   (VALOR_FINANCIADO IN NUMBER,
    ENTRADA IN NUMBER,
     TAXA_JUROS_MENSAL IN NUMBER,
     NUMERO_PRESTACOES IN NUMBER)
     RETURN NUMBER IS
  BEGIN
  RETURN ((VALOR_FINANCIADO- ENTRADA) +
         (((TAXA_JUROS_MENSAL/100) * NUMERO_PRESTACOES) *
         (VALOR_FINANCIADO- ENTRADA)))/NUMERO_PRESTACOES;
  EXCEPTION
        WHEN ZERO_DIVIDE THEN
   RETURN 0;
  END;
/
