echo SHST > c:\pings.txt
tnsping SHST >> c:\pings.txt
echo ORCLPROD >> c:\pings.txt
tnsping ORCLPROD >> c:\pings.txt
echo CLBP >> c:\pings.txt
tnsping CLBP >> c:\pings.txt
echo EPROCT >> c:\pings.txt
tnsping EPROCT >> c:\pings.txt
echo SISE >> c:\pings.txt
tnsping SISE >> c:\pings.txt
echo MULTI >> c:\pings.txt
tnsping SISE >> c:\pings.txt
echo BDCOELBA >> c:\pings.txt
tnsping BDCOELBA >> c:\pings.txt
tnsping DB02 >> c:\pings.txt
tnsping DB02 >> c:\pings.txt
echo CLBP2 >> c:\pings.txt
tnsping CLBP2 >> c:\pings.txt
echo CLPD >> c:\pings.txt
tnsping CLPD >> c:\pings.txt
echo TLMP >> c:\pings.txt
tnsping TLMP >> c:\pings.txt
echo CBD >> c:\pings.txt
tnsping CBD >> c:\pings.txt
echo CBP >> c:\pings.txt
tnsping CBP >> c:\pings.txt
echo CLBC >> c:\pings.txt
tnsping CLBC >> c:\pings.txt
echo CACD >> c:\pings.txt
tnsping CACD >> c:\pings.txt
echo CSNP >> c:\pings.txt
tnsping CSNP >> c:\pings.txt
echo CLBW >> c:\pings.txt
tnsping CLBW >> c:\pings.txt
echo CBQ >> c:\pings.txt
tnsping CBQ >> c:\pings.txt
echo TEC >> c:\pings.txt
tnsping TEC >> c:\pings.txt
echo INV >> c:\pings.txt
tnsping INV >> c:\pings.txt
echo GPLAB >> c:\pings.txt
tnsping GPLAB >> c:\pings.txt
echo CSND >> c:\pings.txt
tnsping CSND >> c:\pings.txt
echo SGMP >> c:\pings.txt
tnsping SGMP >> c:\pings.txt
echo EPROC >> c:\pings.txt
tnsping EPROC >> c:\pings.tx
echo GEOP >> c:\pings.txt
tnsping GEOP >> c:\pings.txt
echo CLPP >> c:\pings.txt
tnsping CLPP >> c:\pings.txt
echo CLBD >> c:\pings.txt
tnsping CLBD >> c:\pings.txt
echo GEOP26.COELBANET >> c:\pings.txt
tnsping GEOP26.COELBANET >> c:\pings.txt
echo CACP >> c:\pings.txt
tnsping CACP >> c:\pings.txt
echo REMEDY >> c:\pings.txt
tnsping REMEDY >> c:\pings.txt
echo SGAM >> c:\pings.txt
tnsping SGAM >> c:\pings.txt
echo RHQ >> c:\pings.txt
tnsping RHQ >> c:\pings.txt
echo RHD >> c:\pings.txt
tnsping RHD >> c:\pings.txt
