SELECT 'ALTER DATABASE RENAME FILE ' || '''' || FILE_NAME || '''' || ' TO ' 
|| '''' 
|| 'R:\Oracle\SAT\Data' || SUBSTR(FILE_NAME,15,40) || '''' || ';'
FROM DBA_DATA_FILES D, DBA_TABLESPACES T
WHERE D.TABLESPACE_NAME = T.TABLESPACE_NAME;
