
ALTER TABLE EGDOC.DOCUMENTS
 ADD (ACCESS_KEY  NVARCHAR2(100));
 
UPDATE EGDOC.DOCUMENTS SET ACCESS_KEY = ACCESS_KEY_OLD;

  
SELECT ACCESS_KEY, ACCESS_KEY_OLD FROM EGDOC.DOCUMENTS
ORDER BY BARCODE 

SELECT ACCESS_KEY, to_char(ACCESS_KEY_OLD) FROM EGDOC.DOCUMENTS
ORDER BY BARCODE 


ALTER table EGDOC.DOCUMENTS DROP COLUMN ACCESS_KEY_OLD;