drop table org_ua

CREATE TABLE ORG_UA (
  UA      VARCHAR2(5),
  DESCR      VARCHAR2(50)
)
ORGANIZATION EXTERNAL (
  TYPE ORACLE_LOADER
  DEFAULT DIRECTORY TEMP
  ACCESS PARAMETERS (
    RECORDS DELIMITED BY NEWLINE
    FIELDS TERMINATED BY ';'
    MISSING FIELD VALUES ARE NULL
    (
  UA      CHAR(50),
  DESCR      cHAR(50)
    )
  )
  LOCATION ('UA.csv')
)
PARALLEL 5
REJECT LIMIT UNLIMITED;