DROP TABLE SYSTEM.CONTROLE_LOGON CASCADE CONSTRAINTS;

CREATE TABLE SYSTEM.CONTROLE_LOGON (
ID NUMBER(8),
SCHEMA VARCHAR2(50) NOT NULL,
DATA_CHECK DATE,
DATA_ULT_LOGIN DATE DEFAULT SYSDATE,
QTDE_LOGON NUMBER(8) )
TABLESPACE TOOLS PCTUSED 40 PCTFREE 10 INITRANS 1 MAXTRANS 255
STORAGE ( INITIAL 128K NEXT 128K PCTINCREASE 0);

 

DECLARE 

NUM_TOT NUMBER ;
NUM_INSE NUMBER:=0;

CURSOR AB IS SELECT USERNAME FROM DBA_USERS ORDER BY 1;

BEGIN

SELECT COUNT(*) INTO NUM_TOT FROM DBA_USERS;

FOR I IN AB LOOP

INSERT INTO CONTROLE_LOGON VALUES (SEQ_LOGON.NEXTVAL,I.USERNAME,SYSDATE,SYSDATE,0);
NUM_INSE:=NUM_INSE +1;
END LOOP;
COMMIT;
DBMS_OUTPUT.put_line('TOTAL: ' || NUM_TOT || ' NUM_INSERIDOS: ' || NUM_INSE); 
END;



--TRG_LOGON_SCHEMAS
--
CREATE OR REPLACE TRIGGER TRG_LOGON_SCHEMAS
AFTER LOGON
ON DATABASE
BEGIN

	UPDATE SYSTEM.CONTROLE_LOGON
	SET DATA_ULT_LOGIN = SYSDATE,
	QTDE_LOGON = QTDE_LOGON +1
	WHERE SCHEMA= USER;
	COMMIT;
END;
/





