REM 
REM 
REM 

ALTER DATABASE DATAFILE 'C:\ORANT\DATABASE\RBS1ORCL.ORA' RESIZE 100M
/

CREATE PUBLIC ROLLBACK SEGMENT "RB_LARGE" TABLESPACE "RBS" STORAGE ( INITIAL 10M NEXT 10M OPTIMAL 20M MINEXTENTS 2 MAXEXTENTS 121)
/

ALTER ROLLBACK SEGMENT "RB_LARGE" ONLINE
/

SET TRANSACTION USE ROLLBACK SEGMENT RB_LARGE;
/

EXIT;
