SELECT 'ANALYZE TABLE '||owner||'.'||TABLE_NAME||' COMPUTE STATISTICS;'
FROM DBA_TABLES
WHERE OWNER = 'SIGABAK'


SELECT 'ANALYZE TABLE '||table_owner||'.'||TABLE_NAME||' PARTITION ('||PARTITION_NAME||') COMPUTE STATISTICS;'
FROM DBA_TAB_PARTITIONS
WHERE TABLE_OWNER = 'SISPACC'
