CREATE TABLESPACE AUTODBATSL01D
DATAFILE
  'D:\ORACLE\SISD\DATA\AUTODBATSL01D.DBF' SIZE 50 M 


LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 5 M;
------- xxxxx -------- ------- xxxxx -------- ------- xxxxx --------
CREATE TABLESPACE AUTODBATSL01I
DATAFILE
  'D:\ORACLE\SISD\DATA\AUTODBATSL01I.DBF' SIZE 50 M 


LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 5 M;