SELECT GRANTEE,GRANTOR||'.'||TABLE_NAME OBJETO,PRIVILEGE  FROM dba_tab_privs
WHERE GRANTEE LIKE '%EMA%'
UNION
SELECT GRANTEE,GRANTOR||'.'||TABLE_NAME OBJETO,PRIVILEGE  FROM dba_tab_privs
WHERE GRANTEE LIKE '%EQMV%'
UNION
SELECT GRANTEE,GRANTOR||'.'||TABLE_NAME OBJETO,PRIVILEGE  FROM dba_tab_privs
WHERE GRANTEE LIKE '%EQAS%'
UNION
SELECT GRANTEE,GRANTOR||'.'||TABLE_NAME OBJETO,PRIVILEGE  FROM dba_tab_privs
WHERE GRANTEE LIKE '%EQAT%'
UNION
SELECT GRANTEE,GRANTOR||'.'||TABLE_NAME OBJETO,PRIVILEGE  FROM dba_tab_privs
WHERE GRANTEE = 'ROLE_REPORT'
ORDER BY 1,3
