CREATE OR REPLACE PROCEDURE SYS.ANALYZE_ALL_TABLES
IS

 ldsErro VARCHAR2(250);

 CURSOR CTAB IS
  SELECT OWNER O, TABLE_NAME TAB
  FROM ALL_TABLES
  WHERE OWNER NOT IN ('SYS','SYSTEM','OUTLN','DBSNMP','BKP','PERSTAT');
BEGIN
 FOR RTAB IN CTAB LOOP
  DBMS_STATS.GATHER_TABLE_STATS(RTAB.O,RTAB.TAB,ESTIMATE_PERCENT=>99,CASCADE=>TRUE);
 END LOOP;

 dbms_output.put_line('ANALYSE REALIZADO COM SUCESSO');

 INSERT INTO RESULT_JOB(NUMERO_JOB,FALHA,DATA,NUMERO_ERRO) VALUES (10,'NAO',SYSDATE,'NAO HOUVE');
 COMMIT;

EXCEPTION
    WHEN OTHERS THEN

      ldsErro := SUBSTR(SQLERRM,1,250);
      dbms_output.put_line('DEU ERRO - ANALYZE_ALL_TABLES');
	  INSERT INTO RESULT_JOB(NUMERO_JOB,FALHA,DATA,NUMERO_ERRO) VALUES (10,'SIM',SYSDATE,'ERRO - ' || ldsErro);
      COMMIT;
	  dbms_output.put_line('DEU ERRO - ANALYZE_ALL_TABLES');
END;
/


GRANT EXECUTE ON  SYS.ANALYZE_ALL_TABLES TO SYSTEM;

