CREATE OR REPLACE PROCEDURE SYS.P_analyze_partition IS

CURSOR C_DATA IS SELECT TABLE_NAME, PARTITION_NAME
	   		  	 				 	   		 FROM DBA_TAB_PARTITIONS
											 WHERE TABLE_OWNER='LOGWATCH';
BEGIN
FOR I IN C_DATA LOOP
 	 EXECUTE IMMEDIATE  'ANALYZE TABLE LOGWATCH.' || I.TABLE_NAME || ' partition '||'('||I.PARTITION_NAME||')'||' compute statistics;' ;
END LOOP;
EXCEPTION
WHEN OTHERS THEN
	 RAISE_APPLICATION_ERROR(-20000,'ERRO NO ANALYZE : ' || SQLERRM);
END;
/

