CREATE OR REPLACE PROCEDURE SYS.P_Analyze IS

CURSOR C_DATA IS SELECT TABLE_NAME
	   		  	 				 	   		 FROM DBA_TABLES
											 WHERE OWNER='LOGWATCH'
											 AND TABLE_NAME NOT IN ('LOGFW', 'LOGNTSEC', 'LOGPROXY', 'LOGWEB');

BEGIN
FOR I IN C_DATA LOOP
 	 EXECUTE IMMEDIATE  'ANALYZE TABLE LOGWATCH.' || I.TABLE_NAME || ' COMPUTE STATISTICS' ;
END LOOP;
EXCEPTION
WHEN OTHERS THEN
	 RAISE_APPLICATION_ERROR(-20000,'ERRO NO ANALYZE : ' || SQLERRM);
END;
/

