-- USUÁRIO LF 

ALTER SESSION SET SQL_TRACE = TRUE;

SELECT sid,serial#, CLIENT_INFO
FROM v$session 
WHERE username = 'LF';

EXECUTE DBMS_SYSTEM.SET_SQL_TRACE_IN_SESSION(21,36791,TRUE);
EXECUTE DBMS_SYSTEM.SET_SQL_TRACE_IN_SESSION(295,61025,TRUE);
EXECUTE DBMS_SYSTEM.SET_SQL_TRACE_IN_SESSION(308,48349,TRUE);
EXECUTE DBMS_SYSTEM.SET_SQL_TRACE_IN_SESSION(1315,8981,TRUE);


ALTER SESSION SET SQL_TRACE = FALSE;

SELECT VALUE FROM V$DIAG_INFO WHERE NAME = 'Default Trace File';