 DROPAR CDC

BEGIN
DBMS_LOGMNR_CDC_PUBLISH.DROP_CHANGE_TABLE(OWNER=>'RPL???',CHANGE_TABLE_NAME=>'CDC_???????????',FORCE_FLAG=>'Y');
END;
/

drop mv

cria mv

CRIAR CDC

BEGIN
DBMS_LOGMNR_CDC_PUBLISH.CREATE_CHANGE_TABLE(OWNER=>'RPL???',
CHANGE_TABLE_NAME=>'CDC_????????????',
CHANGE_SET_NAME=>'SYNC_SET',
SOURCE_SCHEMA=>'RPL???',
SOURCE_TABLE=>'MV???????????',
COLUMN_TYPE_LIST=>'PK NUMBER/CHAR(?)',
CAPTURE_VALUES=>'BOTH',
RS_ID=>'N',
ROW_ID=>'N',
USER_ID=>'Y',
TIMESTAMP=>'Y',
OBJECT_ID=>'N',
SOURCE_COLMAP=>'N',
TARGET_COLMAP=>'N',
OPTIONS_STRING=>NULL);
END;
