CREATE SNAPSHOT LOG ON EMA.SELOS_LOTES
PCTFREE 0
PCTUSED 99
TABLESPACE EMATS01D
STORAGE ( INITIAL 100K NEXT 100K PCTINCREASE 0 )
WITH PRIMARY KEY
/

CREATE SNAPSHOT LOG ON EMA.ACESSO_SETORES
PCTFREE 0
PCTUSED 99
TABLESPACE EMATS01D
STORAGE ( INITIAL 100K NEXT 100K PCTINCREASE 0 )
WITH  (NSEQ_SET, NSEQ_FORN, NSEQ_SET_PMIS)
/