CREATE MATERIALIZED VIEW TESTE 
--   TABLESPACE users 
   REFRESH START WITH SYSDATE  
   NEXT SYSDATE+1/(24*60) 
   AS SELECT * FROM
      SELECT SUM(SAL) FROM EMP 

DROP MATERIALIZED VIEW TESTE 	  
	  
CREATE MATERIALIZED VIEW TESTE 
   REFRESH START WITH SYSDATE+2/(24*60)  
   NEXT SYSDATE+2/(24*60) 
   AS SELECT SUM(SAL) SALARIO FROM EMP 

SELECT * FROM TESTE  
   
CREATE TABLE EMP ( NOME VARCHAR2(20), SAL NUMBER(10) )    

SELECT SYSDATE, A.* FROM DBA_JOBS A

SELECT * FROM DBA_JOBS_RUNNING

drop table emp
