CREATE MATERIALIZED VIEW TESTE
PCTFREE 0
TABLESPACE DATA01
STORAGE (INITIAL 64K NEXT 64K PCTINCREASE 0)
NOPARALLEL
BUILD IMMEDIATE
REFRESH FAST ON COMMIT
ENABLE QUERY REWRITE
AS
SELECT * FROM NUTINFER.TESTE@DB_LINK_DESE