BEGIN DBMS_UTILITY.analyze_schema('SGAM','COMPUTE'); END;


JOB 77 - CLBP - TEMPO: 283870

SELECT TOTAL_TIME, FAILURES FROM DBA_JOBS

SELECT * FROM DBA_JOBS

SELECT TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI')  FROM DUAL

BEGIN DBMS_JOB.REMOVE(10); END;

SELECT * FROM DBA_JOBS

SELECT * FROM USER_JOBS

BEGIN
  DBMS_JOB.ISUBMIT(200,'P_AGENDA;',
                   TO_DATE('29/08/2002 23:00','DD/MM/YYYY HH24:MI'));
END;

BEGIN
  DBMS_JOB.ISUBMIT(100,'P_ATUALIZA_EQPT_TOTAL;',
                   TO_DATE('08/09/2002 03:00','DD/MM/YYYY HH24:MI'),
                   'TRUNC(SYSDATE)+7+3/24');
END;

BEGIN
  DBMS_JOB.ISUBMIT(12,'DBMS_UTILITY.analyze_schema(''MCH'',''COMPUTE'');',
                   TO_DATE('05/05/2002 07:00','DD/MM/YYYY HH24:MI'),
                   'TRUNC(SYSDATE)+7+7/24');
END;

COMMIT

BEGIN DBMS_JOB.REMOVE(100); END;

SELECT * FROM DBA_JOBS

JOB 233 - TEMPO ATUAL: 4628

BEGIN
  DBMS_JOB.ISUBMIT(99,'DBMS_UTILITY.analyze_schema(''GTEL'',''COMPUTE'');',
                  TO_DATE('30/04/2002 05:00','DD/MM/YYYY HH24:MI'));
END;

COMMIT

BEGIN DBMS_UTILITY.analyze_schema('MCH','COMPUTE'); END;

SELECT MIN(LAST_ANALYZED), MAX(LAST_ANALYZED) FROM DBA_TABLES WHERE OWNER = 'MCH'

-- Estou aqui:>
-- hist_indices_chaves_interrup
