CREATE OR REPLACE PROCEDURE EXECUTA(COMANDO VARCHAR2)
AS
V_CURSOR NUMBER;
V_RETURN NUMBER;
BEGIN
 V_CURSOR:=DBMS_SQL.OPEN_CURSOR;
 DBMS_SQL.PARSE(V_CURSOR,COMANDO,DBMS_SQL.NATIVE);
 V_RETURN := DBMS_SQL.EXECUTE(V_CURSOR);
 DBMS_SQL.CLOSE_CURSOR(V_CURSOR);
END;
/
