--CONNECT CHIP/COELBA@CLBD

--REVOKE ALL ON SQLN_EXPLAIN_PLAN FROM PUBLIC;

SELECT * FROM DBA_TAB_PRIVS
WHERE GRANTEE='PUBLIC'
AND OWNER NOT IN ('SYS','SYSTEM','ORDSYS')
ORDER BY 2

SELECT 'REVOKE ' || PRIVILEGE || ' ON ' || TABLE_NAME  || ' FROM ' || GRANTEE || ';'
FROM DBA_TAB_PRIVS
WHERE GRANTEE='PUBLIC'
AND OWNER NOT IN ('SYS','SYSTEM','ORDSYS')
AND OWNER ='SISPACC'


