select grantee || ' -------------------------' || privilege from DBA_sys_privs
WHERE GRANTEE not in ('SYS','SYSTEM','MDSYS','PTN993289','CLB239950','DBA','CONNECT','ORDSYS','ORDPLUGINS','RESOURCE','EXP_FULL_DATABASE','IMP_FULL_DATABASE') 
AND PRIVILEGE NOT IN ('CREATE SESSION','UNLIMITED TABLESPACE','CONNECT','RESOURCE','SELECT ANY TABLE') 
AND (PRIVILEGE LIKE '%ALTER%' OR PRIVILEGE LIKE '%DROP%') order by 1