LOAD DATA
INFILE     'E:\tmp\UA.csv'
BADFILE         'E:\tmp\UA.bad'
DISCARDFILE     'E:\tmp\UA.log'
INSERT INTO TABLE UA
FIELDS TERMINATED BY ";" OPTIONALLY ENCLOSED BY '"' TRAILING NULLCOLS
(ID,DESCR)