SELECT 
COUNT(*)
--* 
--'ALTER SYSTEM KILL SESSION '|| '''' || SID ||',' || SERIAL# || '''' || ';' 
FROM V$SESSION 
WHERE USERNAME ='OPERADOR'
AND TO_CHAR(LOGON_TIME,'DD/MM/RRRR') <> TO_CHAR(SYSDATE,'DD/MM/RRRR')
ORDER BY LOGON_TIME
