select 'REVOKE '||PRIVILEGE||' FROM '||GRANTEE||';' from dba_sys_privs
where privilege like '%ANY%'
AND GRANTEE NOT LIKE 'DBA%'
AND GRANTEE NOT IN ('DBA','SYS','SYSTEM','SPOT','OUTLN','ADSGF','DBSNMP','SASMASTER','OEM_MONITOR','JAVADEBUGPRIV',
'EXP_FULL_DATABASE','IMP_FULL_DATABASE','AQ_ADMINISTRATOR_ROLE')
