spool /oracle/admin/sac/create/crdb2.log

REM ********** ALTER SYSTEM TABLESPACE *********
ALTER TABLESPACE SYSTEM
DEFAULT STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0);
ALTER TABLESPACE SYSTEM
MINIMUM EXTENT 64K;

REM ********** TABLESPACE FOR Tool **********
CREATE TABLESPACE TOOLS DATAFILE '/oracle/oradata/sac/tools01.dbf' SIZE 50M REUSE
 AUTOEXTEND ON NEXT 32K
MINIMUM EXTENT 32K
DEFAULT STORAGE ( INITIAL 32K NEXT 32K MINEXTENTS 1 MAXEXTENTS 4096 PCTINCREASE 0);

REM ********** TABLESPACE FOR ROLLBACK **********
CREATE TABLESPACE RBS DATAFILE '/oracle/oradata/sac/rbs01.dbf' SIZE 300M REUSE
 AUTOEXTEND OFF
MINIMUM EXTENT 512K
DEFAULT STORAGE ( INITIAL 1M NEXT 1M MINEXTENTS 10 MAXEXTENTS 4096);

REM ********** TABLESPACE FOR TEMPORARY **********
CREATE TABLESPACE TEMP DATAFILE '/oracle/oradata/sac/temp01.dbf' SIZE 512M  REUSE
 AUTOEXTEND OFF
MINIMUM EXTENT 64K
DEFAULT STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 1 MAXEXTENTS UNLIMITED PCTINCREASE 0) TEMPORARY;

REM ********** TABLESPACE FOR USER **********
CREATE TABLESPACE USERS DATAFILE '/oracle/oradata/sac/users01.dbf' SIZE 20M REUSE
 AUTOEXTEND ON NEXT 64K
MINIMUM EXTENT 64K
DEFAULT STORAGE ( INITIAL 32K NEXT 32K MINEXTENTS 1 MAXEXTENTS 4096 PCTINCREASE 0);

REM ********** TABLESPACE FOR INDEX **********
CREATE TABLESPACE INDX DATAFILE '/oracle/oradata/sac/indx01.dbf' SIZE 20M REUSE
 AUTOEXTEND ON NEXT 64K
MINIMUM EXTENT 64K
DEFAULT STORAGE ( INITIAL 32K NEXT 32K MINEXTENTS 1 MAXEXTENTS 4096 PCTINCREASE 0);


REM ********** TABLESPACE FOR INDEX **********
CREATE TABLESPACE TS_CTWEB_I1 DATAFILE '/oracle/oradata/sac/ctwebi101.ind' SIZE 1300M REUSE
 AUTOEXTEND ON NEXT 512K
MINIMUM EXTENT 64K
DEFAULT STORAGE ( INITIAL 64K NEXT 64K MINEXTENTS 1 MAXEXTENTS 4096 PCTINCREASE 0);

REM ********** TABLESPACE FOR INDEX **********
CREATE TABLESPACE TS_CTWEB01 DATAFILE '/oracle/oradata/sac/ctweb0101.dbf' SIZE 1300M REUSE
 AUTOEXTEND ON NEXT 512K
MINIMUM EXTENT 128K
DEFAULT STORAGE ( INITIAL 128K NEXT 128K MINEXTENTS 1 MAXEXTENTS 4096 PCTINCREASE 0);



REM **** Creating four rollback segments ****************
CREATE PUBLIC ROLLBACK SEGMENT R01 TABLESPACE RBS
STORAGE ( OPTIMAL 10240K );
CREATE PUBLIC ROLLBACK SEGMENT R02 TABLESPACE RBS
STORAGE ( OPTIMAL 10240K );
CREATE PUBLIC ROLLBACK SEGMENT R03 TABLESPACE RBS
STORAGE ( OPTIMAL 10240K );
CREATE PUBLIC ROLLBACK SEGMENT R04 TABLESPACE RBS
STORAGE ( OPTIMAL 10240K );
CREATE PUBLIC ROLLBACK SEGMENT R05 TABLESPACE RBS
STORAGE ( OPTIMAL 10240K );
CREATE PUBLIC ROLLBACK SEGMENT R06 TABLESPACE RBS
STORAGE ( OPTIMAL 10240K );
CREATE PUBLIC ROLLBACK SEGMENT R07 TABLESPACE RBS
STORAGE ( OPTIMAL 10240K );
CREATE PUBLIC ROLLBACK SEGMENT R08 TABLESPACE RBS
STORAGE ( OPTIMAL 10240K );
CREATE PUBLIC ROLLBACK SEGMENT R09 TABLESPACE RBS
STORAGE ( OPTIMAL 10240K );
CREATE PUBLIC ROLLBACK SEGMENT R10 TABLESPACE RBS
STORAGE ( OPTIMAL 10240K );
CREATE PUBLIC ROLLBACK SEGMENT R11 TABLESPACE RBS
STORAGE ( OPTIMAL 10240K );
CREATE PUBLIC ROLLBACK SEGMENT R12 TABLESPACE RBS
STORAGE ( OPTIMAL 10240K );
CREATE PUBLIC ROLLBACK SEGMENT R13 TABLESPACE RBS
STORAGE ( OPTIMAL 10240K );
CREATE PUBLIC ROLLBACK SEGMENT R14 TABLESPACE RBS
STORAGE ( OPTIMAL 10240K );
CREATE PUBLIC ROLLBACK SEGMENT R15 TABLESPACE RBS
STORAGE ( OPTIMAL 10240K );
CREATE PUBLIC ROLLBACK SEGMENT R16 TABLESPACE RBS
STORAGE ( OPTIMAL 10240K );
CREATE PUBLIC ROLLBACK SEGMENT R17 TABLESPACE RBS
STORAGE ( OPTIMAL 10240K );
CREATE PUBLIC ROLLBACK SEGMENT R18 TABLESPACE RBS
STORAGE ( OPTIMAL 10240K );
CREATE PUBLIC ROLLBACK SEGMENT R19 TABLESPACE RBS
STORAGE ( OPTIMAL 10240K );
CREATE PUBLIC ROLLBACK SEGMENT R20 TABLESPACE RBS
STORAGE ( OPTIMAL 10240K );

ALTER ROLLBACK SEGMENT "R01" ONLINE;
ALTER ROLLBACK SEGMENT "R02" ONLINE;
ALTER ROLLBACK SEGMENT "R03" ONLINE;
ALTER ROLLBACK SEGMENT "R04" ONLINE;
ALTER ROLLBACK SEGMENT "R05" ONLINE;
ALTER ROLLBACK SEGMENT "R06" ONLINE;
ALTER ROLLBACK SEGMENT "R07" ONLINE;
ALTER ROLLBACK SEGMENT "R08" ONLINE;
ALTER ROLLBACK SEGMENT "R09" ONLINE;
ALTER ROLLBACK SEGMENT "R10" ONLINE;
ALTER ROLLBACK SEGMENT "R11" ONLINE;
ALTER ROLLBACK SEGMENT "R12" ONLINE;
ALTER ROLLBACK SEGMENT "R13" ONLINE;
ALTER ROLLBACK SEGMENT "R14" ONLINE;
ALTER ROLLBACK SEGMENT "R15" ONLINE;
ALTER ROLLBACK SEGMENT "R16" ONLINE;
ALTER ROLLBACK SEGMENT "R17" ONLINE;
ALTER ROLLBACK SEGMENT "R18" ONLINE;
ALTER ROLLBACK SEGMENT "R19" ONLINE;
ALTER ROLLBACK SEGMENT "R20" ONLINE;


REM **** SYS and SYSTEM users ****************
alter user sys temporary tablespace TEMP;
alter user system temporary tablespace TEMP;
spool off



spool /oracle/admin/sac/create/crdb3.log

@/oracle/817/rdbms/admin/catalog.sql

@/oracle/817/rdbms/admin/catproc.sql
@/oracle/817/rdbms/admin/caths.sql
## @/oracle/817/rdbms/admin/otrcsvr.sql
@/oracle/817/rdbms/admin/catexp.sql
connect system/manager
@/oracle/817/sqlplus/admin/pupbld.sql
spool off

