rem  ==========================================================================
rem  Name  : DBMap.sql 
rem  date  : 2-Dec-1998
rem  author: R. Schierbeek, Bytelife Netherlands
rem
rem  comp  : Oracle8.1.5 upwards !
rem  uses  : v$database,dba_tablespaces,dba_segments,dba_data_files,v$logfile.
rem  desc  : Shows database information: owners, # of tables, indexes etc.
rem  output: Generates a DBMAP.htm file in C:\temp\
rem 
rem  Instruction: * Change the spool file or directory, when needed. 
rem               * Connect as SYSTEM.
rem               * Start the script.
rem  ==========================================================================
rem  Modifications:
rem  25-jun-01  spool to C:\temp\DBMAP||name.htm
rem  26-jul-01  Auto-extending datafiles
rem  16-aug-01  Tables with chained rows
rem  16-sep-02  Added "and I.owner=S1.owner" for identical tables in 1 db.
rem  12-dec-02  Auto-extending info now from dba_data_files.
rem  22-jan-03  table width should be max. 700 for printing
rem  ==========================================================================
clear columns breaks


define spooldir=C:\temp\
define table='<table width=660 cellpadding=1 cellspacing=0 border=0>'

set feed off head off echo off verify OFF wrap OFF trimspool ON
set linesize 300

prompt spooling to file &spooldir\DBMAP.htm ...

set term OFF verify off echo off feed off wrap off heading off 
spool tmpspool.sql
   select 'spool &spooldir\DBMAP'||name||'.htm'
   from  v$database  ;
spool off
@tmpspool.sql
host del tmpspool.sql

prompt <html><head>
prompt <meta name="description" content="generated by dbMap.sql- bytelife bv">
prompt <title>Database information </title> </head><body>
prompt <a name="top"></a>

prompt <table width=700 cellpadding=2 cellspacing=0 border=3>
prompt <tr bgcolor="#EFEFEF"><td colspan=4 align="center">
prompt <font size="5" color="#333366"> Database report </font>
prompt <tr bgcolor="#EFEFEF"><td>
select '<font size="4" color="#333366">database: <b>'||name from v$database
/
select '<td> date: '||to_char(sysdate,'HH24:MI') from dual
/
select '<td>machine: '||HOST_NAME from v$instance
/

prompt <tr bgcolor="#EFEFEF">
select  '<td><font color="#333366">started: <b>'||to_char(STARTUP_TIME,'DD-MON-YY HH24:MI')
	,'<td>archiver: '||archiver
	,'<td>version : '||version    
from   v$instance
/

prompt </table><p></p>


prompt <h3> Tables and indexes </h3>

prompt <blockquote> <font face="Courier" size="2">

prompt &&table
prompt <tr bgcolor="#EFEFEF"><td> owner
prompt  <td> tablespace 
prompt  <td> type
prompt <td align="right"> Nr. of objects
set wrap on

select '<tr><td> '||owner
      ,'<td> <a href="#'||tablespace_name||'">'||tablespace_name||'</a>'
      ,'<td> '||segment_type
      ,'<td align="right">'||count(*)
from   sys.dba_segments
where  owner not in ('SYS','SYSTEM','AURORA$JIS$UTILITY$','OUTLN')
group by owner,tablespace_name,segment_type
/
prompt </table></blockquote></font>


prompt <h3> Tablespace types </h3>
prompt <blockquote> <font face="Courier" size="2">

prompt &&table
prompt <tr bgcolor="#EFEFEF">
prompt  <td> Tablespace name <td> Extent management
prompt  <td> Allocation type
prompt  <td align="right"> Initial extent
prompt  <td align="right"> Next extent
prompt  <td align="right"> Min. extent length

select '<tr><td>'||     tablespace_name
      ,'<td> '||extent_management
      ,'<td> '||allocation_type
      ,'<td align="right">'||initial_extent
      ,'<td align="right">'||next_extent
      ,'<td align="right">'||min_extlen
from   sys.DBA_tablespaces
order by tablespace_name
/
prompt </table></blockquote></font>


prompt <h3> Tablespaces and datafiles </h3>
prompt <blockquote> <font face="Courier" size="2">

prompt &&table
prompt <tr bgcolor="#EFEFEF"><td> tablespace 
prompt  <td> file name
prompt  <td align="right"> Kbyte

select '<tr><td> <a name='||tablespace_name||'>'||tablespace_name||'</a>' 
      ,'<td> '||file_name
      ,'<td align="right"><font face="Courier" size="2">'||trunc(bytes/1024,0)
from   sys.dba_data_files 
order by tablespace_name,file_name
/
prompt </table> <p>

prompt &&table
prompt <tr bgcolor="#EFEFEF"><td> tablespace 
prompt  <td> status <td> contents
set wrap on

select '<tr><td> '
        ||tablespace_name||'</a>' 
      ,'<td> '||status
      ,'<td> '||decode(contents,'TEMPORARY'
                               ,'<font color="blue">TEMPORARY'
                               ,contents)                   
from   sys.dba_tablespaces
order by tablespace_name
/
prompt </table></blockquote></font><p>


prompt <h3> Auto-extending datafiles </h3>
prompt <blockquote> <font face="Courier" size="1">

prompt &&table
prompt <tr bgcolor="#EFEFEF"> <td> datafile 
prompt  <td align="right"> Mbyte <td align="right"> Maxsize Mb
prompt  <td align="right"> Space <td align="right"> Incr.Mb 
prompt <tr bgcolor="#EFEFEF"><td colspan="5">

col name     format A60
col Mbyte    format 999,999
col Maxsize  format 999,999
col Space    format 999,999
col Increase format 999,999
set null [off]

select '<tr><td>'
	,F.file_name  name
  	,'<td align="right">',F.bytes/1048567      Mbyte
	,'<td align="right">',(maxbytes/1048567)   Maxsize
	,'<td align="right">',((maxbytes - F.bytes) /1048567)  space
	,'<td align="right">',(increment_by * value)/1048567   Increase
from   dba_data_files  F
	,v$parameter     P
where	P.name           = 'db_block_size'
and   F.autoextensible = 'YES'
order by F.tablespace_name,F.file_name
/

set null ''

prompt </table></blockquote></font>

prompt Note: "Space" is not the free space in the file - it's the space until autoextend runs into "Maxbytes" <p>
prompt <a href="#top">goto top</a>


prompt <h3> System Events </h3>
prompt <blockquote> <font face="Courier" size="2">

prompt &&table
prompt <tr bgcolor="#EFEFEF"><td> Event
prompt  <td> average_wait

select '<tr><td>'||event   event
      ,'<td>',average_wait wait
from   v$system_EVENT
where  event like 'db_file_scatter%'
or     event like 'db_file_sequential%'
 
prompt </table></blockquote></font>


prompt <h3> Control and Log files</h3>
prompt <blockquote> <font face="Courier" size="2">

prompt &&table
prompt <tr bgcolor="#EFEFEF">  
prompt  <td> group   <td>Logfile member

col member format A40
select '<tr><td>',group#
      ,'<td>'||member 
from  v$logfile
order by group#,member ;

prompt <tr bgcolor="#EFEFEF">  
prompt  <td> nr   <td>Controlfile name 

select '<tr><td>',rownum
      ,'<td>'||   name
from  v$controlfile ;
prompt </table></blockquote></font>


prompt <h3> Archive, Init and Alert files</h3>
prompt <blockquote> <font face="Courier" size="2">

prompt &&table
prompt <tr bgcolor="#EFEFEF">  
prompt  <td> name   <td> location

col value format A70 trunc
select '<tr><td>',initcap(name)||' : '
      ,'<td>'||  value  from   v$parameter where  name in 
  ('ifile','background_dump_dest','log_archive_dest' ) ;

prompt </table></blockquote></font>


prompt <h3> Misplaced indexes </h3>
prompt <blockquote> <font face="Courier" size="2">

prompt &&table
prompt <tr bgcolor="#EFEFEF">  
prompt   <td>Table owner <td>Table name
prompt   <td>Index owner <td>Index name

select '<tr><td>'||T.owner
      ,'<td>'||T.table_name
      ,'<td>'||I.owner
      ,'<td>'||I.index_name
from   dba_tables   t
      ,dba_indexes  i
where  T.table_name = I.table_name
and    T.owner      = I.table_owner
and    I.owner != T.owner
order by T.owner,I.owner
/
prompt </table></blockquote></font>


col SX for A30 head 'Index' trunc
col SY for A30 head 'Table' trunc
col I1 for 999,999,999 head 'Index size'
col TS for 999,999,999 head 'Table size' 

prompt <h3>Indexes which are quite large compared to table they're on</h3>
prompt <blockquote><font face="Courier" size="2">

prompt &&table
prompt <tr bgcolor="#EFEFEF">  
prompt  <td>Index <td align="right"> Kbyte <td align="right"> extents
prompt  <td>Table <td align="right"> Kbyte <td align="right"> extents

select '<tr><td>'||         S1.segment_name SX
      ,'<td align="right">',S1.bytes/1024   I1
      ,'<td align="right">',S1.extents
      ,'<td>'||             S2.segment_name SY
      ,'<td align="right">',S2.bytes/1024   TS
      ,'<td align="right">'||S2.extents
from  dba_segments S1
     ,dba_segments S2
     ,dba_indexes  I
where I.index_name = S1.segment_name
and   I.table_name = S2.segment_name
and   I.owner      = S1.owner
and   I.owner      = S2.owner
and   S1.partition_name is null
and   S2.partition_name is null
and   S1.bytes >= S2.bytes*1.4
and   S1.bytes > 2000000
and   I.owner != 'SYS'
and   I.PARTITIONED = 'NO'
/

prompt </table></blockquote> </font>


prompt <h3> Procedures and Package body's</h3>
prompt <blockquote> <font face="Courier" size="2">

prompt &&table
prompt <tr bgcolor="#EFEFEF"> <td>Owner
prompt   <td> Name <td>Type <td>status <td align="right"> lines 

select '<tr><td>'||S.Owner
      ,'<td>'||name
      ,'<td>'||initcap(type)
      ,'<td>'||lower(status)
      ,'<td align="right">'||max(line) Lines
from   dba_source  S
      ,dba_objects O
where  S.name  = O.object_name
and    S.type  = O.object_type
and    S.owner != 'SYS'
and    S.type in ('PACKAGE BODY','PROCEDURE','FUNCTION')
group by S.owner,name,initcap(type),lower(status)
order by S.owner,name
/

prompt </table></blockquote></font> 


prompt <h3> Objects changed in the last 5 days ordered by LAST_DDL_TIME descending.</h3>
prompt <blockquote> <font face="Times" size="1">

prompt &&table
prompt <tr bgcolor="#EFEFEF"> <td> Owner <td> Name <td>part. <br> name 
prompt   <td>Type <td> Created <td>Last DDL<br>Change <td>status

col O1 for A22 trunc
col N2 for A40 trunc
col D1 for A16
col D2 for A16

select '<tr><td>'||owner   O1
      ,'<td>'||object_name N2
      ,'<td>'||subobject_name
      ,'<td>'||initcap(object_type)
      ,'<td>'||to_char(created,'DD-MM-YY')       D1
      ,'<td>'||to_char(last_ddl_time,'DD-MM-YY') D2
      ,'<td>'||lower(status)
from  dba_objects
where sysdate - LAST_DDL_TIME < 5
and   status != 'INVALID'
AND   ROWnum <= 100
order by trunc(last_ddl_time) DESC,object_name
/
prompt </table></font>
prompt <li> Note: a maximum of 100 rows is selected !</li>
prompt </blockquote>


prompt <h3> Invalid objects </h3>
prompt <blockquote> <font face="Times" size="1">

prompt &&table
prompt <tr bgcolor="#EFEFEF"> <td> Owner  <td> Name
prompt   <td> Name <td> Created <td>Last DDL<br>Change <td>status

select '<tr><td>'||owner   O1
      ,'<td>'||object_name N2
      ,'<td>'||initcap(object_type)
      ,'<td>'||to_char(created,'DD-MM-YY')       D1
      ,'<td>'||to_char(last_ddl_time,'DD-MM-YY') D2
      ,'<td>'||lower(status)
from  dba_objects
where status='INVALID'
order by owner,object_name
/
prompt </table></blockquote></font> 

prompt <h3> Number of analyzed tables </h3>
prompt <blockquote> <font face="Times" size="1">

prompt &&table
prompt <tr bgcolor="#EFEFEF"><td> Owner <td> Count

select '<tr><td>'||owner O1
      ,'<td>'||count(*)  N2
from   dba_tables
where  num_rows >= 0
group by owner 
/
prompt </table></blockquote></font> 


prompt <h3> Tables with chained rows (only analyzed tables)</h3>
prompt <blockquote> <font face="Times" size="1">

prompt &&table
prompt <tr bgcolor="#EFEFEF"><td> Owner <td>table name <td align="right"> Totalrows
prompt   <td align="right">Chained rows <td align="right">chainded/<br>total rows Pct

select '<tr><td>'||owner   O1
      ,'<td>'||table_name  N2
      ,'<td align="right">'||num_rows
      ,'<td align="right">'||chain_cnt
      ,'<td align="right">'||trunc((100 * chain_cnt/num_rows),1 )
from   dba_tables
where  chain_cnt > 0
order by chain_cnt  DESC
/
prompt </table></blockquote></font> 

prompt <hr>
prompt <font size="-1">
prompt <a href="#top">goto top</a>
prompt <p align="right">
select 'Generated on : '||to_char(sysdate,'DD-MON-YYYY') from dual ;

prompt </body></html>
spool OFF

set head on feed on term ON linesize 90
prompt  End of dbMap script
