rem  ======================================================================
rem  name  : Indexes.sql
rem  author: R. Schierbeek, Bytelife bv Netherlands
rem  date  : 29-feb-99
rem  desc  : Shows Indexes for all tables of 1 owner
rem  usage : Run as System, enter the name of the owner you want to analyze.
rem  compatible : Oracle 7, Oracle 8
rem  ======================================================================

set linesize 100 echo OFF timing OFF trimspool ON wrap ON
define owner=&ownername
prompt Spooling to file index.htm. Wait a few moments ...  ....
set pages 0 feed OFF echo OFF termout OFF heading OFF verify OFF
spool C:\temp\index.htm
prompt <html><head>
prompt <meta name="description" content="Generated by indMap.sql - Bytelife bv">
prompt <title>All indexes of 1 user </title> </head>
prompt <body bgcolor="white"><font size="2">

select '<b>Database name : '||name||' date: '||to_char(sysdate,'DD-MON-YYYY')||'</b>'
from   sys.v_$DATABASE
/
select distinct '<b>machine: '||machine||'</b>' from v$session
where username is null 
and   machine  is not null
/

select '<h3>Tables and indexes of: &&owner </h3>' from sys.dual ;
prompt <ol>
select ' <li><a href="#'||substr(Table_name,1,24)||'">'||substr(Table_name,1,24)||'</a><b> *'||num_rows||'</b>'
from    DBA_tables
where   owner = upper('&&owner')
order by Table_name
;
set pages 0 feed OFF echo OFF termout OFF heading OFF
prompt </ol>
prompt <h3>INDEXES</h3><font size="3">
prompt <table border="1" cellpadding="1" cellspacing="0">
prompt <tr><td>Table owner </td>
prompt <td colspan="3"><b>Table name</b></td></tr>
prompt <tr><td align="right">position</td><td>column_name</td>
prompt <td><b>index name</td><td><font color="red">uniqueness</td></tr>

break on T0 on T1 on T2 on T3
select '<tr><td><a name="'||substr(I.Table_name,1,24)||'"></a>' T0
      ,I.Table_owner||'</td>' T1
      ,'<td colspan="3"><b>'||I.Table_name||'</b></td></tr>' T2
      ,'<tr><td align="right"><font color="black">'||COL.column_position||'</td>'
      ,'<td><font color="black">'||substr(COL.column_name,1,24)||'</td>'
      ,'<td><b><a name="'||I.index_name||'"></a>'
      ,I.index_name||decode(I.uniqueness,
              'UNIQUE','</td><td><font color="red">'
                      ,'</td><td>')
            ||I.uniqueness||' *'||I.DISTINCT_KEYS||'</td></tr>' T3
from   DBA_ind_columns COL
      ,DBA_indexes     I
where  I.table_owner   = upper('&&owner')
and    I.index_name    = COL.index_name
and    I.table_owner =  COL.table_owner 
order by I.Table_name,I.index_name,COL.column_position
;
prompt </table><pre>
prompt </body></html>
set pages 100 head ON term ON feed ON
spool OFF
prompt  OUTPUT in file  C:\temp\index.htm
undefine owner

