rem  ======================================================================
rem  name       : Storage.sql
rem  author     : R. Schierbeek, Bytelife bv Netherlands
rem  date       : Sep 1996
rem  compatible : Oracle 7, Oracle 8
rem  uses       : dba_segments
rem  
rem  Description:
rem   * Checks table and index storage clauses for all owners.
rem   * Creates a spool script C:\temp\ DBnameYYMONDD.chk
rem   * Change "extents >=1" to "extents >=2" for a more compact list.
rem  ======================================================================
rem  Date      Modification
rem  ---------  -----------------------------------------------------------
rem  15-Aug-00 html format
rem  31-Dec-00 smaller fonts
rem  02-Aug-01 added table which shows a too high or low growth rate 
rem  07-Apr-02 order by S.owner,S.segment_type,S.bytes 
rem  27-Aug-02 table/index columns smaller font
rem  ======================================================================

set verify off echo off term off feed off define ON
set wrap off head off pages 100

spool tmpspool.sql
      select 'spool C:\temp\store'||name||'_'||to_char(sysdate,'yymondd')||'.htm'
      from sys.v_$DATABASE;
spool off
@tmpspool.sql
host del tmpspool.sql
set head off feed off term off trimspool ON
prompt <html><head>
prompt <meta name="description" content="generated by storage.sql- bytelife bv">
prompt <title>storage clauses </title></head>
prompt <body bgcolor="white" font size=2>

prompt <table cellpadding=2 width="650" cellpadding="3" cellspacing="0" border=2>
prompt <tr bgcolor="#EFEFEF"><td colspan="3" align="center">
prompt <font size="5" color="#333366"> Storage report </font>
prompt <tr bgcolor="#EFEFEF"><td>
select '<font size="4" color="#333366">database: <b>'||name  from v$database ;
select '<td><font size="4"> date: '||to_char(sysdate,'DD-mon-YYYY')  from dual;
select '<td><font size="4"> time: '||to_char(sysdate,'HH:MI')  from dual;
prompt </table>
prompt <p></p>

set wrap OFF trimspool ON term OFF pages 0
set linesize 500

prompt <font face="Times New Roman" size=2>
prompt <table width=650 border=1 cellpadding=1 cellspacing=0 bordercolor=#d8d0c8>
prompt <tr bgcolor="#EFEFEF"><td height=22 align="center">
prompt       <font face="Verdana" color=steelblue> Owner
prompt   <td colspan=6> current extent size (past) 
prompt   <td colspan=4> modifiable size (future)
prompt <tr align=right><td>
prompt <td valign=bottom><font color=blue size=2> type
prompt <td>  MIN <br>size Kb
prompt <td>  MAX <br>size Kb
prompt <td> <font color="green">AVG <br>size Kb
prompt <td> Nr. of <br> objects 
prompt <td> <b> Nr.of <br>extents 
prompt <td> <font color="blue"> Next <br>Kb
prompt <td nowrap> <font color="blue">Next/</font>
prompt      <font color="green"><br>AVG %
prompt <td>  Pct <br>incr.
prompt <td>  Max <br>extents 

col C1 format A88
col average for 99,999,999 
col min     for 99,999,999 
col max     for 99,999,999 
col next    for 9,999,999
col Growth   for 999999
col pct_I   for 999
col ext     for 9999

break on C1
select '<tr align=right><td align=center>','<font face="Verdana" color=steelblue size=2><b>'||
        initcap(substr(S.owner,1,14))||'<tr align=right><td>' C1
      ,'<td><font face="Times New Roman" color=blue>'||lower(S.segment_type)
      ,'<td>',min(S.bytes/1024)  MIN
      ,'<td>',max(S.bytes/1024)  MAX
      ,'<td>',avg(S.bytes/1024)  AVERAGE
      ,'<td>',count(*) 
      ,'<td> <b>'||max(S.extents) Ext
      ,'<td>',next_extent/1024    NEXT
      ,'<td>',(next_extent/avg(S.bytes))*100 Growth
      ,'<td>',pct_increase PctI
      ,'<td>'||decode(max_extents,2147483645,'unltd',max_extents)  MaxExt
from   sys.DBA_SEGMENTS S
where S.owner not in ('SYS','SYSTEM')
and   extents >= 1
group by S.owner,S.segment_type,next_extent,pct_increase,max_extents
/

prompt </table>

prompt <p> <font size=2>
prompt <ul>
prompt <li> The information in this report is from DBA_SEGMENTS.
prompt <li> The growth rate (<font color="blue">Next/</font><font color="green">AVG</font>) is 
prompt the size of the next extent compared to the current size of the object.
prompt <li> Note: to avoid fragmentation keep the growth rate >=8%, except for large tables. 
prompt </ul>

prompt <H4>The following objects have a too high or low growth rate </H4>
prompt </font>

prompt <font face="Times New Roman" color=steelblue size=2>
prompt <table width=650 border=1 cellpadding=1 cellspacing=0 bordercolor="#d8d0c8">
prompt <tr bgcolor="#EFEFEF"><td height=22 align="center">
prompt                  <font color=steelblue> Owner
prompt   <td colspan=4> current extent size (past) 
prompt   <td colspan=4> modifiable size (future)
prompt <tr align=right><td>
prompt <td align=left>  <br> Segment name
prompt <td valign=bottom> type
prompt <td> <font color="green"> Size <br>size Kb
prompt <td> <b> Nr.of <br>extents 
prompt <td> <font color="blue"> Next  <br>Kb
prompt <td nowrap>  Growth
prompt       <font color="blue"><br>Next/ 
prompt       <font color="green"> Size
prompt <td>  Pct <br>incr.
prompt <td>  Max <br>extents 

prompt <tr bgcolor="#EFEFEF"><td colspan=9> <b> Growth rate < 8% </b>

select '<tr align=right><td align=center>','<font color=steelblue size=2>'||
        initcap(substr(S.owner,1,14))||'<tr align=right><td>' C1
      ,'<td align=left>'||substr(S.segment_name,1,20)
      ,'<td>'||lower(S.segment_type)
      ,'<td>',S.bytes/1024       Min
      ,'<td> <b>'||S.extents     Ext
      ,'<td>',next_extent/1024   NEXT
      ,'<td> <b>',(next_extent/S.bytes)*100 Growth
      ,'<td>',pct_increase PctI
      ,'<td>'||decode(max_extents,2147483645,'unltd',max_extents)  MaxExt
from   sys.DBA_SEGMENTS S
where  S.owner not in ('SYS','SYSTEM')
and    extents >= 1
and    (next_extent/S.bytes)*100 < 8
order by S.owner,S.segment_type,S.bytes desc
/
prompt <tr bgcolor="#EFEFEF"><td colspan=9> <b> Growth rate >= 60% (too high) </b>

select '<tr align=right><td align=center>','<font color=steelblue size=2>'||
       initcap(substr(S.owner,1,14))||'<tr align=right><td>' C1
      ,'<td align=left>'||substr(S.segment_name,1,20)
      ,'<td>'||lower(S.segment_type)
      ,'<td>',S.bytes/1024       Min
      ,'<td> <b>'||S.extents     Ext
      ,'<td>',next_extent/1024   NEXT
      ,'<td> <b>',(next_extent/S.bytes)*100 Growth
      ,'<td>',pct_increase PctI
      ,'<td>'||decode(max_extents,2147483645,'unltd',max_extents)  MaxExt
from   sys.DBA_SEGMENTS S
where  S.owner not in ('SYS','SYSTEM')
and    (next_extent/S.bytes)*100 >= 60
and    extents >= 2
order by S.owner,S.segment_type,S.bytes desc
/

prompt </table>
prompt </font><p><hr>
prompt </body></html>
spool off
set term ON head ON feed ON pages 100
prompt End of script.
prompt See spoolfile in C:\temp\store...htm


