SELECT 'ALTER TABLE ' || OWNER || '.' || TABLE_NAME || ' LOGGING;'  
FROM DBA_TABLES
WHERE LOGGING ='NO'
UNION
SELECT 'ALTER INDEX ' || OWNER || '.' || INDEX_NAME || ' LOGGING;'  
FROM DBA_INDEXES
WHERE LOGGING ='NO'
