/* Formatted on 2009/11/11 10:19 (Formatter Plus v4.8.8) */
DROP TABLESPACE ts1mdl_aud_dwh INCLUDING CONTENTS AND DATAFILES;

CREATE TABLESPACE ts1mdl_aud_dwh DATAFILE
  'L:\DWHDES\ORADATA\TS1MDL_AUD_DWH01.dbf' SIZE 2048 m AUTOEXTEND ON
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1 m
BLOCKSIZE 16 k
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE ts1mdl_aud_dwh_p2000 DATAFILE
  'L:\DWHDES\ORADATA\TS1MDL_AUD_DWH_P2000_01.dbf' SIZE 2048 m AUTOEXTEND ON,
  'L:\DWHDES\ORADATA\TS1MDL_AUD_DWH_P2000_02.dbf' SIZE 2048 m AUTOEXTEND ON
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1 m
BLOCKSIZE 16 k
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE ts1mdl_aud_dwh_p2001 DATAFILE
  'L:\DWHDES\ORADATA\TS1MDL_AUD_DWH_P2001_01.dbf' SIZE 2048 m AUTOEXTEND ON,
  'L:\DWHDES\ORADATA\TS1MDL_AUD_DWH_P2001_02.dbf' SIZE 2048 m AUTOEXTEND ON
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1 m
BLOCKSIZE 16 k
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE ts1mdl_aud_dwh_p2002 DATAFILE
  'L:\DWHDES\ORADATA\TS1MDL_AUD_DWH_P2002_01.dbf' SIZE 2048 m AUTOEXTEND ON,
  'L:\DWHDES\ORADATA\TS1MDL_AUD_DWH_P2002_02.dbf' SIZE 2048 m AUTOEXTEND ON
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1 m
BLOCKSIZE 16 k
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE ts1mdl_aud_dwh_p2003 DATAFILE
  'L:\DWHDES\ORADATA\TS1MDL_AUD_DWH_P2003_01.dbf' SIZE 2048 m AUTOEXTEND ON,
  'L:\DWHDES\ORADATA\TS1MDL_AUD_DWH_P2003_02.dbf' SIZE 2048 m AUTOEXTEND ON
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1 m
BLOCKSIZE 16 k
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE ts1mdl_aud_dwh_p2004 DATAFILE
  'L:\DWHDES\ORADATA\TS1MDL_AUD_DWH_P2004_01.dbf' SIZE 2048 m AUTOEXTEND ON,
  'L:\DWHDES\ORADATA\TS1MDL_AUD_DWH_P2004_02.dbf' SIZE 2048 m AUTOEXTEND ON
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1 m
BLOCKSIZE 16 k
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE ts1mdl_aud_dwh_p2005 DATAFILE
  'L:\DWHDES\ORADATA\TS1MDL_AUD_DWH_P2005_01.dbf' SIZE 2048 m AUTOEXTEND ON,
  'L:\DWHDES\ORADATA\TS1MDL_AUD_DWH_P2005_02.dbf' SIZE 2048 m AUTOEXTEND ON
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1 m
BLOCKSIZE 16 k
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE ts1mdl_aud_dwh_p2006 DATAFILE
  'L:\DWHDES\ORADATA\TS1MDL_AUD_DWH_P2006_01.dbf' SIZE 2048 m AUTOEXTEND ON,
  'L:\DWHDES\ORADATA\TS1MDL_AUD_DWH_P2006_02.dbf' SIZE 2048 m AUTOEXTEND ON
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1 m
BLOCKSIZE 16 k
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE ts1mdl_aud_dwh_p2007 DATAFILE
  'L:\DWHDES\ORADATA\TS1MDL_AUD_DWH_P2007_01.dbf' SIZE 2048 m AUTOEXTEND ON,
  'L:\DWHDES\ORADATA\TS1MDL_AUD_DWH_P2007_02.dbf' SIZE 2048 m AUTOEXTEND ON
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1 m
BLOCKSIZE 16 k
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE ts1mdl_aud_dwh_p2008 DATAFILE
  'L:\DWHDES\ORADATA\TS1MDL_AUD_DWH_P2008_01.dbf' SIZE 2048 m AUTOEXTEND ON,
  'L:\DWHDES\ORADATA\TS1MDL_AUD_DWH_P2008_02.dbf' SIZE 2048 m AUTOEXTEND ON
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1 m
BLOCKSIZE 16 k
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE ts1mdl_aud_dwh_p2009 DATAFILE
  'L:\DWHDES\ORADATA\TS1MDL_AUD_DWH_P2009_01.dbf' SIZE 2048 m AUTOEXTEND ON,
  'L:\DWHDES\ORADATA\TS1MDL_AUD_DWH_P2009_02.dbf' SIZE 2048 m AUTOEXTEND ON
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1 m
BLOCKSIZE 16 k
SEGMENT SPACE MANAGEMENT AUTO;