SELECT	 A.GROUP#,
		 B.MEMBER,
		 A.THREAD#, 
		 A.SEQUENCE#, 
		 A.BYTES/1024/1024 MB, 
		 A.MEMBERS,
		 A.ARCHIVED, 
		 A.STATUS, 
		 A.FIRST_CHANGE#, 
		 A.FIRST_TIME
FROM V$LOG A, V$LOGFILE B
WHERE A.GROUP# = B.GROUP#
ORDER BY A.GROUP#;