CREATE OR REPLACE PROCEDURE TSINMETRO.Pr_Envia_Email (pDEST IN VARCHAR2,pASSUNTO IN VARCHAR2, pFLAG IN CHAR,pQUANT IN NUMBER)
   IS

   -- PARAMETROS:
   -- pDEST = DESTINO DO EMAIL
   -- pASSUNTO = ASSUNTO
   -- pFLAG = FLAG PARA SABER SE FOI COM SUCESSO OU NAO >> '0' COM SUCESSO
   -- pQUANT = QUANTIDADE DE REGISTRO GRAVADOS PASSADOS POR PARAMETRO

   MAILHOST VARCHAR2(30) := '10.20.1.8'; -- IP DO SERVIDOR DE EMAIL DO IBAMETRO
   REMETENTE VARCHAR2(30) := 'pr_envia_email@ibametro.ba.gov.br'; -- EMAIL DO REMETENTE DA MENSAGEM
   DESTINATARIO VARCHAR2(1000) := pDEST;  -- EMAIL DO DESTINATARIO DA MENSAGEM
   ASSUNTO VARCHAR2(255) := pASSUNTO; -- TITULO DA MENSAGEM
   MAIL_CONN UTL_SMTP.CONNECTION;

   CRLF VARCHAR2(2) := CHR(13) || CHR(10); -- QUEBRA DE LINHA
   MESQ VARCHAR2(2000); -- TEXTO DA MENSAGEM

   BEGIN


	  	 MAIL_CONN := UTL_SMTP.OPEN_CONNECTION(MAILHOST,25);
		 MESQ := 'Date: ' || TO_CHAR(SYSDATE,'dd Mon yy hh24:mi:ss') || CRLF || 'Subject: ' || ASSUNTO || CRLF || 'To: ' ||
	     DESTINATARIO || CRLF || CRLF;
		 IF pFLAG = '0' THEN
		 	 MESQ := MESQ || 'Mensagem: ANALYZE PROD_IBA REALIZADO COM SUCESSO' || CRLF || CRLF || 'QUANTIDADE DE TABELAS ANALIZADAS :' || pQUANT || CRLF || CRLF ||'DATA: ' || TO_CHAR(SYSDATE,'DD/MM/YYYY hh24:mi:ss') || CRLF || CRLF;
		 ELSE
		 	 MESQ := MESQ || 'Mensagem: ANALYZE PROD_IBA COM PROBLEMA' || CRLF || CRLF || 'DATA: ' || TO_CHAR(SYSDATE,'DD/MM/YYYY hh24:mi:ss') || CRLF || CRLF;
		 END IF;



	 	 UTL_SMTP.HELO(MAIL_CONN,MAILHOST);
		 UTL_SMTP.MAIL(MAIL_CONN,REMETENTE);
		 UTL_SMTP.RCPT(MAIL_CONN,DESTINATARIO);
	 	 UTL_SMTP.DATA(MAIL_CONN,MESQ);
	 	 UTL_SMTP.QUIT(MAIL_CONN);



	  EXCEPTION
		   WHEN OTHERS THEN
	  	   RAISE_APPLICATION_ERROR(-20002,'Impossivel enviar e-mail.' || CRLF || 'Erro: ' ||SQLERRM);


   END ;
/


GRANT EXECUTE ON  TSINMETRO.PR_ENVIA_EMAIL TO R_EXECUTE;

GRANT EXECUTE ON  TSINMETRO.PR_ENVIA_EMAIL TO SYS;

