CREATE OR REPLACE FORCE VIEW "DBACENTER"."MONITOR_SESSION"  AS
  SELECT /*+ rule */
         s.status, si.sid, s.serial#, p.spid, p.pid,s.type,
         s.username , s.osuser , s.server ,
         s.machine , s.MODULE, s.terminal ,
         s.program program_session , p.program program_process,
         s.logon_time , lockwait ,
         si.physical_reads , si.block_gets ,
         si.consistent_gets ,
         si.block_changes ,
         si.consistent_changes, s.process,
         s.sql_address,
         floor(last_call_et/3600)||':'||floor(mod(last_call_et,3600)/60)||':'|| mod(mod(last_call_et,3600),60) elapsed_time,
         decode(command,
            1,'CREATE TABLE',
            2,'INSERT',
            3,'SELECT',
            4,'CREATE CLUSTER',
            5,'ALTER CLUSTER',
            6,'UPDATE',
            7,'DELETE',
            8,'DROP CLUSTER',
            9,'CREATE INDEX',
            10,'DROP INDEX',
            11,'ALTER INDEX',
            12,'DROP TABLE',
            15,'ALTER TABLE',
            16,'DROP SEQUENCE',
            17,'GRANT OBJECT',
            18,'REVOKE OBJECT',
            19,'CREATE SYNONYM',
            20,'DROP SYNONYM',
            21,'CREATE VIEW',
            22,'DROP VIEW',
            23,'VALIDATE INDEX',
            24,'CREATE PROCEDURE',
            25,'ALTER PROCEDURE',
            26,'LOCK',
            28,'RENAME',
            34,'CREATE DATABASE',
            35,'ALTER DATABASE',
            36,'CREATE ROLLBACK SEG',
            37,'ALTER ROLLBACK SEG',
            38,'DROP ROLLBACK SEG',
            39,'CREATE TABLESPACE',
            40,'ALTER TABLESPACE',
            41,'DROP TABLESPACE',
            42,'ALTER SESSION',
            43,'ALTER USER',
            44,'COMMIT',
            45,'ROLLBACK',
            46,'SAVEPOINT',
            47,'PL/SQL EXECUTE',
            49,'ALTER SYSTEM',
            50,'EXPLAIN',
            51,'CREATE USER',
            53,'DROP USER',
            57,'CREATE CONTROL FILE',
            59,'CREATE TRIGGER',
            60,'ALTER TRIGGER',
            61,'DROP TRIGGER',
            62,'ANALYZE TABLE',
            63,'ANALYZE INDEX',
            64,'ANALYZE CLUSTER',
            68,'DROP PROCEDURE',
            71,'CREATE MATERIALIZED VIEW LOG',
            72,'ALTER MATERIALIZED VIEW LOG',
            73,'DROP MATERIALIZED VIEW LOG',
            74,'CREATE MATERIALIZED VIEW',
            75,'ALTER MATERIALIZED VIEW',
            76,'DROP MATERIALIZED VIEW',
            85,'TRUNCATE TABLE',
            91,'CREATE FUNCTION',
            92,'ALTER FUNCTION',
            93,'DROP FUNCTION',
            94,'CREATE PACKAGE',
            95,'ALTER PACKAGE',
            96,'DROP PACKAGE',
            97,'CREATE PACKAGE BODY',
            98,'ALTER PACKAGE BODY',
            99,'DROP PACKAGE BODY',
            103,'SESSION REC',
            116,'EXECUTE PROCEDURE',
            122,'NETWORK ERROR',
            161,'ALTER JAVA',
            162,'DROP JAVA',
            170,'CALL METHOD',
            182,'UPDATE INDEXES',
            183,'ALTER OPERATOR',command) command
    FROM v$session s, v$process p, sys.v_$sess_io si
   WHERE s.paddr = p.addr(+)
     AND si.sid(+) = s.sid
     AND (s.username IS NOT NULL);
/

CREATE or replace VIEW DBACENTER.monitor_wait AS
SELECT a.sid, b.username, a.event,a.wait_time, a.seconds_in_wait, a.state, b.status,
       b.action, p.spid, b.server
FROM v$session_wait a, v$session b, v$process p
WHERE a.event NOT IN ('pmon timer', 'rdbms ipc message', 'smon timer', 'SQL*Net message from client')
AND  a.sid = b.sid
AND  b.paddr = p.addr(+)
AND  a.wait_time >= 0;
/

