CREATE PROFILE DBAPOLO LIMIT CONNECT_TIME 6;

ALTER PROFILE DBAPOLO LIMIT  SESSIONS_PER_USER 5;

CREATE USER DBACENTER PROFILE DBAPOLO
    IDENTIFIED BY polodba_2014 DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    ACCOUNT UNLOCK;
GRANT SELECT ON  "SYS"."V_$PROCESS" TO "DBACENTER";
GRANT SELECT ON  "SYS"."V_$SESSION" TO "DBACENTER";
GRANT SELECT ON  "SYS"."V_$SESSION_WAIT" TO "DBACENTER";
GRANT SELECT ON  "SYS"."V_$SESS_IO" TO "DBACENTER";
GRANT "CONNECT" TO "DBACENTER";
GRANT "SELECT_CATALOG_ROLE" TO "DBACENTER";

-- Se o PROFILE for criado depois
ALTER USER DBACENTER PROFILE DBAPOLO;

grant create view  to DBACENTER;
-- Opcional - apenas se o cliente autorizar que nosso usuáo mate sessõ
grant alter system to DBACENTER;

grant select on dba_jobs to DBACENTER;

alter user DBACENTER quota unlimited on users;

