DROP INDEX LF.SYS_C0073898;
DROP INDEX LF.SYS_IL0000146988C00004$$;
DROP INDEX LF.UK_STG_RESUMO_IMPOSTO_001;

SELECT DBMS_METADATA.GET_DDL('INDEX','SYS_C0073898','LF') from dual;

    CREATE UNIQUE INDEX "LF"."SYS_C0073898" ON
        "LF"."STG_RESUMO_IMPOSTO" (
            "SRI_ID"
        )
            PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
                STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
                DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
            TABLESPACE "TS_COMPLY"

SELECT DBMS_METADATA.GET_DDL('INDEX','SYS_IL0000146988C00004$$','LF') from dual;

CREATE UNIQUE INDEX "LF"."SYS_IL0000146988C00004$$" ON "LF"."STG_RESUMO_IMPOSTO" ( PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
    FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
TABLESPACE "TS_COMPLY"
    PARALLEL ( DEGREE 0 INSTANCES 0 ) 

SELECT DBMS_METADATA.GET_DDL('INDEX','UK_STG_RESUMO_IMPOSTO_001','LF') from dual;

    CREATE UNIQUE INDEX "LF"."UK_STG_RESUMO_IMPOSTO_001" ON
        "LF"."STG_RESUMO_IMPOSTO" (
            "CUS_ID",
            "BTI_ID",
            "SRI_DT_FIN",
            "BTO_ID",
            "BUS_ID",
            "SRI_DT_INI"
        )
            PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
                STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
                DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
            TABLESPACE "TS_COMPLY"