select 'ALTER TABLE '||OWNER||'.'||TABLE_NAME||' MOVE LOB ('||COLUMN_NAME||') STORE AS ( TABLESPACE TS128MDS_LOB_SGA ENABLE  STORAGE IN ROW CHUNK 8192 PCTVERSION 10 NOCACHE NOLOGGING INDEX ( TABLESPACE TS128MDS_LOB_SGA STORAGE (INITIAL 128m MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) ) );' 
    from dba_tab_columns
    where 1 = 1
    and owner not in ('SYS','SYSTEM','OUTLN','WMSYS')
    and data_type in ('BLOB','CLOB','LONG',
    'LONG RAW','RAW','SDD_ACC_PRIV_LIST','SDD_SYS_PRIV_LIST','UNDEFINED')