SELECT ltrim(rtrim(upper('%CUSTOMER_NAME%'))) CUSTOMER_NAME
	   ,ltrim(rtrim('%REGION%')) REGION
	   ,ltrim(rtrim('%HOSTNAME%')) HOSTNAME
	   ,ltrim(rtrim( '%INSTANCENAME%')) INSTANCE_NAME
	   ,SQL_ID
       ,EXECS
       ,ELA_SECS
       ,AVG_SECS
       ,RATIO_TO_REPORT(ELA_SECS) OVER () AS OVERALL_RATIO
FROM (
  SELECT B.SQL_ID,
         SUM(B.EXECUTIONS_DELTA) AS EXECS,
         ROUND(((SUM(B.ELAPSED_TIME_DELTA))/1000000),2) AS ELA_SECS,
         ROUND( (SUM(B.ELAPSED_TIME_DELTA)/1000000)/CASE WHEN SUM(B.EXECUTIONS_DELTA) = 0 THEN 1 ELSE SUM(B.EXECUTIONS_DELTA) END,2)  AS AVG_SECS
  FROM sys.WRM$_SNAPSHOT A,
       sys.WRH$_SQLSTAT  B
  WHERE A.DBID            = B.DBID
    AND A.INSTANCE_NUMBER = B.INSTANCE_NUMBER
    AND A.SNAP_ID         = B.SNAP_ID
    AND A.BEGIN_INTERVAL_TIME >= TRUNC(SYSDATE-7) 
  GROUP BY B.SQL_ID
  ORDER BY 3 DESC
) WHERE ROWNUM <= 15