STARTUP NOMOUNT
CREATE CONTROLFILE set DATABASE "TESTE01hml" RESETLOGS  NOARCHIVELOG
--  SET STANDBY TO MAXIMIZE PERFORMANCE
    MAXLOGFILES 5
    MAXLOGMEMBERS 3
    MAXDATAFILES 100
    MAXINSTANCES 1
    MAXLOGHISTORY 226
LOGFILE
  GROUP 1 'E:\ORACLE\TESTE01hml\REDO\REDO01.LOG'  SIZE 100M,
  GROUP 2 'E:\ORACLE\TESTE01hml\REDO\REDO02.LOG'  SIZE 100M,
  GROUP 3 'E:\ORACLE\TESTE01hml\REDO\REDO03.LOG'  SIZE 100M
-- STANDBY LOGFILE
DATAFILE
  'E:\ORACLE\TESTE01hml\DATA\SYSTEM01.DBF',
  'E:\ORACLE\TESTE01hml\DATA\UNDOTBS01.DBF',
  'E:\ORACLE\TESTE01hml\DATA\USERS01.DBF',
  'E:\ORACLE\TESTE01hml\DATA\REPOSITORY01.DBF'
CHARACTER SET WE8ISO8859P1
;
exit